import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@/styles/css/globals.css";
import { QueryProviders, ProviderTheme as ThemeProvider } from "@/lib/context";

const raleway = Raleway({ subsets: ["latin"], weight: ["500", "600"] });

export const metadata: Metadata = {
  title: "MCTool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body className={raleway.className}>
        <QueryProviders>
          <ThemeProvider>{children}</ThemeProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
