import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@/app/_assets/css/globals.css";
import { ProviderTheme as ThemeProvider } from "@/lib/context";

const raleway = Raleway({ subsets: ["latin"], weight: ["500", "600"] });

export const metadata: Metadata = {
  title: "MCTool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={raleway.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
